# Generated by Django 4.0.4 on 2022-05-31 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_bedrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposited_at', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('ammount', models.FloatField()),
                ('attachment', models.FileField(upload_to='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
        ),
    ]
