# Generated by Django 4.0.4 on 2022-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
