# Generated by Django 4.0.4 on 2022-07-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_alter_payment_member_historicalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('ammount', models.FloatField(verbose_name='saldo')),
                ('currency', models.CharField(max_length=128, verbose_name='moneda')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='ammount',
            field=models.FloatField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='attachment',
            field=models.TextField(max_length=100, verbose_name='adjunto'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='reference',
            field=models.CharField(max_length=128, verbose_name='num referencia'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='verificado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ammount',
            field=models.FloatField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attachment',
            field=models.FileField(upload_to='', verbose_name='adjunto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=128, verbose_name='num referencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='verificado'),
        ),
    ]
