# Generated by Django 4.0.4 on 2022-09-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0006_providerpayment_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayment',
            name='description',
            field=models.TextField(default='NO HAY DESCRIPCION', verbose_name='descripción'),
            preserve_default=False,
        ),
    ]
