# Generated by Django 4.0.4 on 2022-09-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0007_providerpayment_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerpayment',
            options={'verbose_name': 'Pago Proveedor'},
        ),
        migrations.AddField(
            model_name='providerpayment',
            name='provider',
            field=models.CharField(default='NO PROVEDOR', max_length=128, verbose_name='proveedor'),
            preserve_default=False,
        ),
    ]
