# Generated by Django 4.0.4 on 2022-10-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0008_alter_providerpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerpayment',
            options={'verbose_name': 'Pago Proveedor', 'verbose_name_plural': 'Pagos a proveedores'},
        ),
    ]
