
VALOR_UR = 1358
VALOR_GC = 3500
COSTO_CUARTO_UR = 2.965 # UNIDADES REAJUSTABLES
FONDO_MANTENIMIENTO = 0.42 # UNIDADES REAJUSTABLES
VALOR_INACOOP = 754


def gen_cuota_social(socio):
    return VALOR_UR * ((COSTO_CUARTO_UR * socio.bedrooms) + FONDO_MANTENIMIENTO)



