# Generated by Django 4.0.4 on 2022-04-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('second_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='second_name')),
                ('first_surname', models.CharField(max_length=128, verbose_name='first_surname')),
                ('second_surname', models.CharField(max_length=128, verbose_name='second_surname')),
                ('titular', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='phone_number')),
                ('member_number', models.SmallIntegerField(db_index=True, verbose_name='member_number')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
