# Generated by Django 4.0.4 on 2022-05-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cuota_social', 'Cuota social'), ('gastos_comunes', 'Gastos comunes'), ('fondo_socorro', 'Fondo socorro'), ('atraso_cuota', 'Atraso cuota'), ('falta_asamblea', 'Falta asamblea'), ('falta_obra', 'Falta obra'), ('convenio_social', 'Convenio social'), ('prestamo_inacoop', 'Préstamo inacoop'), ('salon_comunal', 'Salon comunal'), ('salon_otros', 'Salon otros'), ('saldo_anterior', 'Saldo anterior'), ('otros', 'Otros')], max_length=256, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('ammount', models.FloatField(verbose_name='ammount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
        ),
    ]
