# Generated by Django 4.0.4 on 2022-05-19 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bedrooms',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
