# Generated by Django 4.0.4 on 2022-09-01 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_historicalmember_historicaldebt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Socio', 'verbose_name_plural': 'historical Socios'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterField(
            model_name='debt',
            name='ammount',
            field=models.FloatField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha creación'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='type',
            field=models.CharField(choices=[('cuota_social', 'Cuota social'), ('gastos_comunes', 'Gastos comunes'), ('fondo_socorro', 'Fondo socorro'), ('atraso_cuota', 'Atraso cuota'), ('falta_asamblea', 'Falta asamblea'), ('falta_obra', 'Falta obra'), ('convenio_social', 'Convenio social'), ('prestamo_inacoop', 'Préstamo inacoop'), ('salon_comunal', 'Salon comunal'), ('salon_otros', 'Salon otros'), ('saldo_anterior', 'Saldo anterior'), ('otros', 'Otros')], max_length=256, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicaldebt',
            name='ammount',
            field=models.FloatField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='historicaldebt',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='fecha creación'),
        ),
        migrations.AlterField(
            model_name='historicaldebt',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicaldebt',
            name='type',
            field=models.CharField(choices=[('cuota_social', 'Cuota social'), ('gastos_comunes', 'Gastos comunes'), ('fondo_socorro', 'Fondo socorro'), ('atraso_cuota', 'Atraso cuota'), ('falta_asamblea', 'Falta asamblea'), ('falta_obra', 'Falta obra'), ('convenio_social', 'Convenio social'), ('prestamo_inacoop', 'Préstamo inacoop'), ('salon_comunal', 'Salon comunal'), ('salon_otros', 'Salon otros'), ('saldo_anterior', 'Saldo anterior'), ('otros', 'Otros')], max_length=256, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='bedrooms',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='num dormitorios'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='primer nombre'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='first_surname',
            field=models.CharField(max_length=128, verbose_name='primer apellido'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='member_number',
            field=models.SmallIntegerField(db_index=True, verbose_name='numero de socio'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='numero de telefono'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='second_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='segundo nombre'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='second_surname',
            field=models.CharField(max_length=128, verbose_name='segundo apellido'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bedrooms',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='num dormitorios'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='primer nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_surname',
            field=models.CharField(max_length=128, verbose_name='primer apellido'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_number',
            field=models.SmallIntegerField(db_index=True, verbose_name='numero de socio'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='numero de telefono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='second_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='segundo nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='second_surname',
            field=models.CharField(max_length=128, verbose_name='segundo apellido'),
        ),
    ]
